general: &general
  timeout: 5000
  adapter: postgresql
  pool: 5
  min_messages: WARNING

development:
  <<: *general
  database: cruise_control_dev
  host: localhost

test:
  <<: *general
  database: cruise_control_test
  host: localhost

production:
  <<: *general
  host: host
  database: cruise_control_test
